using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Logo.CARI
{

    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class DEFNFLDSLIST
    {
        public Meta Meta { get; set; }
    }

    public class GENIUSFLDSLIST
    {
        public Meta Meta { get; set; }
    }

    public class Meta
    {
        public string href { get; set; }
        public string mediaType { get; set; }
        public string apiVersion { get; set; }
    }

    public class NOTES
    {
        public Meta Meta { get; set; }
    }

    public class Root
    {
        public string TAX_ID { get; set; }
        public string CONTACT2 { get; set; }
        public string CONTACT1_TEL { get; set; }
        public string CONTACT2_TEL { get; set; }
        public string PP_GROUP_CODE { get; set; }
        public string CONTACT3 { get; set; }
        public string CONTACT3_TEL { get; set; }
        public string GL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string POST_LABEL { get; set; }
        public string SENDER_LABEL { get; set; }
        public string PAYMENT_CODE { get; set; }
        public string SECTOR_MAIN_CODE { get; set; }
        public string SECTOR_SUB_CODE { get; set; }

        public int INTERNAL_REFERENCE { get; set; }
        public int? RECORD_STATUS { get; set; }
        public int? ACCOUNT_TYPE { get; set; }
        public string CODE { get; set; }
        public string TITLE { get; set; }
        public string AUXIL_CODE { get; set; }
        public string AUTH_CODE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string DISTRICT { get; set; }
        public string TOWN_CODE { get; set; }
        public string TOWN { get; set; }
        public string CITY_CODE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string TELEPHONE1 { get; set; }
        public string TELEPHONE1_CODE { get; set; }
        public string TELEPHONE2 { get; set; }
        public string TELEPHONE2_CODE { get; set; }
        public string FAX { get; set; }
        public string FAX_CODE { get; set; }
        public string TAX_OFFICE { get; set; }
        public string TAX_OFFICE_CODE { get; set; }
        public string CONTACT { get; set; }
        public double? DISCOUNT_RATE { get; set; }
        public int? EXTENREF { get; set; }
        public int? PAYMENTREF { get; set; }
        public string E_MAIL { get; set; }
        public int? REMINDER_TYPE { get; set; }
        public int? CORRESP_LANG { get; set; }
        public int? BLOCKED { get; set; }
        public int? CURRENCY { get; set; }
        public int? TEXTINC { get; set; }
        public int? DATA_SITEID { get; set; }
        public int? DATA_REFERENCE { get; set; }
        public string TRADING_GRP { get; set; }
        public int? CREATED_BY { get; set; }
        public DateTime DATE_CREATED { get; set; }
        public int? HOUR_CREATED { get; set; }
        public int? MIN_CREATED { get; set; }
        public int? SEC_CREATED { get; set; }
        public int? MODIFIED_BY { get; set; }
        public DateTime DATE_MODIFIED { get; set; }
        public int? HOUR_MODIFIED { get; set; }
        public int? MIN_MODIFIED { get; set; }
        public int? SEC_MODIFIED { get; set; }
        public int? DEBT_TRCK_TYPE { get; set; }
        public int? XRTDIF_TYPE { get; set; }
        public NOTES NOTES { get; set; }
        public int CREDIT_TYPE { get; set; }
        public double? CREDIT_LIMIT { get; set; }
        public double? CREDIT_BALANCED { get; set; }
        public double? RISKFACT_CHQ { get; set; }
        public double? RISKFACT_PROMNT { get; set; }
        public int? ACTION_CREDHOLD { get; set; }
        public int? ACCOUNTREF { get; set; }
        public int? CENTERREF { get; set; }
        public int? PROJECTREF { get; set; }
        public int? XML_ATTRIBUTE { get; set; }
        public int? USE_REP_RISK { get; set; }
        public double? RISK_LIMIT { get; set; }
        public double? RISK_BALANCED { get; set; }
        public int? ORD_SEND_METHOD { get; set; }
        public int? DSP_SEND_METHOD { get; set; }
        public int? INV_SEND_METHOD { get; set; }
        public int? SUBSCRIBER_STATUS { get; set; }
        public int? PAYMENT_TYPE { get; set; }
        public int? LAST_SEND_REM_LEV { get; set; }
        public int? EXT_ACC_FLAGS { get; set; }
        public int? ORD_SEND_FORMAT { get; set; }
        public int? DSP_SEND_FORMAT { get; set; }
        public int? INV_SEND_FORMAT { get; set; }
        public int? REM_SEND_FORMAT { get; set; }
        public int? CL_ORD_FREQ { get; set; }
        public int? ORD_DAY { get; set; }
        public string LOGOID { get; set; }
        public int? LID_Confirmed { get; set; }
        public int? E_BSNS_SEND_TYPE { get; set; }
        public int? LDX_DEF_ORDER_STAT { get; set; }
        public int? LDX_DEF_ORDER_PRC { get; set; }
        public int? ITR_SEND_METHOD { get; set; }
        public int? ITR_SEND_FORMAT { get; set; }
        public int? IMG2INC { get; set; }
        public int? INVOICE_PRNT_CNT { get; set; }
        public GENIUSFLDSLIST GENIUSFLDSLIST { get; set; }
        public DEFNFLDSLIST DEFNFLDSLIST { get; set; }
        public int? WFLOWCARDREF { get; set; }
        public int? PARENTCLREF { get; set; }
        public int? CODE_CHANGED { get; set; }
        public int? COLLECTINV { get; set; }
        public int? PIECEORDINFLICT { get; set; }
        public int? PURCHBRWS { get; set; }
        public int? SALESBRWS { get; set; }
        public int? IMPBRWS { get; set; }
        public int? EXPBRWS { get; set; }
        public int? FINBRWS { get; set; }
        public int? COLLATRLRISK_TYPE { get; set; }
        public int? COLLRISK_OVER { get; set; }
        public int? COLLRISK_ORD_RISK_OVER { get; set; }
        public int? COLLRISK_DESP_RISK_OVER { get; set; }
        public int? COLLRISK_USE_REP_RISK { get; set; }
        public double? COLLRISK_PCOLLATRL_TOTAL { get; set; }
        public double? COLLRISK_REP_PCOLLATRL_TOT { get; set; }
        public double? COLLRISK_SCOLLATRL_TOTAL { get; set; }
        public double? COLLRISK_TOTAL { get; set; }
        public double? COLLRISK_REP_RISK_TOTAL { get; set; }
        public double? COLLRISK_DESP_TOTAL { get; set; }
        public double? COLLRISK_REP_DESP_RISK_TOT { get; set; }
        public double? COLLRISK_LIMIT { get; set; }
        public double? COLLRISK_REP_LIMIT { get; set; }
        public double? COLLRISK_BALANCED { get; set; }
        public double? COLLRISK_REP_BALANCED { get; set; }
        public double? COLLRISK_ORD_RISK_TOTAL { get; set; }
        public double? COLLRISK_REP_ORD_RISK_TOT { get; set; }
        public double? COLLRISK_ORD_RISK_TOT_SUGG { get; set; }
        public double? COLLRISK_REP_ORD_RISK_TOT_SUG { get; set; }
        public int? COLLRISK_SEP_CS_RISK_TOT { get; set; }
        public int? COLLRISK_CS_RISK_OVER { get; set; }
        public double? COLLRISK_CS_RISK_TOTAL { get; set; }
        public double? COLLRISK_REP_CS_RISK_TOT { get; set; }
        public int? GRPFIRMNR { get; set; }
        public int? CONSCODEREF { get; set; }
        public string AUXIL_CODE2 { get; set; }
        public string AUXIL_CODE3 { get; set; }
        public string AUXIL_CODE4 { get; set; }
        public string AUXIL_CODE5 { get; set; }
        public int? EBANKCODE { get; set; }
        public int? OFF_SEND_METHOD { get; set; }
        public int? OFF_SEND_FORMAT { get; set; }
        public int? RISK_TYPE1 { get; set; }
        public int? RISK_TYPE2 { get; set; }
        public int? RISK_TYPE3 { get; set; }
        public int? RISK_TYPE4 { get; set; }
        public int? RISK_TYPE5 { get; set; }
        public int? RISK_TYPE6 { get; set; }
        public int? RISK_TYPE7 { get; set; }
        public int? RISK_TYPE8 { get; set; }
        public int? RISK_TYPE9 { get; set; }
        public int? RISK_TYPE10 { get; set; }
        public int? RISK_TYPE11 { get; set; }
        public int? RISK_TYPE12 { get; set; }
        public int? RISK_TYPE13 { get; set; }
        public int? RISK_TYPE14 { get; set; }
        public int? RISK_TYPE15 { get; set; }
        public double? CST_CEK_RISK_FACTOR { get; set; }
        public double? CST_SENET_RISK_FACTOR { get; set; }
        public int? RISK_GRP_CONTROL { get; set; }
        public int? ACTION_CREDHOLD_ORD { get; set; }
        public int? ACTION_CREDHOLD_DESP { get; set; }
        public int? ACTION_CREDHOLD_ACC { get; set; }
        public int? ACTION_CREDHOLD_CST_CS { get; set; }
        public int? ACTION_CREDHOLD_MY_CS { get; set; }
        public int? RISK_CTRL_TYPE { get; set; }
        public double? ACC_RISK_TOTAL { get; set; }
        public double? REP_ACC_RISK_TOTAL { get; set; }
        public double? CST_CS_RISK_TOTAL { get; set; }
        public double? REP_CST_CS_RISK_TOTAL { get; set; }
        public double? MY_CS_RISK_TOTAL { get; set; }
        public double? REP_MY_CS_RISK_TOTAL { get; set; }
        public double? ORD_RISK_TOTAL { get; set; }
        public double? REP_ORD_RISK_TOTAL { get; set; }
        public double? ORD_RISK_TOTAL_SUGG { get; set; }
        public double? REP_ORD_RISK_TOTAL_SUGG { get; set; }
        public double? DESP_RISK_TOTAL { get; set; }
        public double? REP_DESP_RISK_TOTAL { get; set; }
        public double? ACC_RISK_LIMIT { get; set; }
        public double? REP_ACC_RISK_LIMIT { get; set; }
        public double? CST_CS_RISK_LIMIT { get; set; }
        public double? REP_CST_CS_RISK_LIMIT { get; set; }
        public double? MY_CS_RISK_LIMIT { get; set; }
        public double? REP_MY_CS_RISK_LIMIT { get; set; }
        public double? DESP_RISK_LIMIT { get; set; }
        public double? REP_DESP_RISK_LIMIT { get; set; }
        public double? ORD_RISK_LIMIT { get; set; }
        public double? REP_ORD_RISK_LIMIT { get; set; }
        public double? ORD_RISK_LIMIT_SUGG { get; set; }
        public double? REP_ORD_SIRK_LIMIT_SUGG { get; set; }
        public double? ACC_RISK_BALANCED { get; set; }
        public double? REP_ACC_RISK_BALANCED { get; set; }
        public double? CST_CS_RISK_BALANCED { get; set; }
        public double? REP_CST_CS_RISK_BALANCED { get; set; }
        public double? MY_CS_RISK_BALANCED { get; set; }
        public double? REP_MY_CS_RISK_BALANCED { get; set; }
        public double? DESP_RISK_BALANCED { get; set; }
        public double? REP_DESP_RISK_BALANCED { get; set; }
        public double? ORD_RISK_BALANCED { get; set; }
        public double? REP_ORD_RISK_BALANCED { get; set; }
        public double? ORD_RISK_BALANCED_SUGG { get; set; }
        public double? REP_ORD_RISK_BALANCED_SUGG { get; set; }
        public int? LOAN_GRP_CTRL { get; set; }
        public int? EBUS_DATA_SEND_TYPE { get; set; }
        public int? INI_STATUS_FLAGS { get; set; }
        public int? SLS_ORDER_STATUS { get; set; }
        public int? SLS_ORDER_PRICE { get; set; }
        public int? SAME_ITEM_CODE_USE { get; set; }
        public int? IMAGE_SIZE { get; set; }
        public int? PERSCOMPANY { get; set; }
        public string TCKNO { get; set; }
        public int? EXT_SEND_METHOD { get; set; }
        public int? EXT_SEND_FORMAT { get; set; }
        public int? ADDTOREFLIST { get; set; }
        public int? ORD_RISK_OVER_SUGG { get; set; }
        public string CASH_CODE { get; set; }
        public int? CASHREF { get; set; }
        public int? USED_IN_PERIODS { get; set; }
        public string E_MAIL2 { get; set; }
        public string E_MAIL3 { get; set; }
        public int? RSKLIM_CNTRL { get; set; }
        public int? DUEDATE_CNTRL { get; set; }
        public int? AGING_CNTRL { get; set; }
        public int? AGING_DAY { get; set; }
        public int? ORD_PRIORITY { get; set; }
        public int? ACCEPT_EINV { get; set; }
        public int? PROFILE_ID { get; set; }
        public int? PURC_ORDER_STATUS { get; set; }
        public int? PURC_ORDER_PRICE { get; set; }
        public int? CS_DOWNS_RISK { get; set; }
        public int? CST_CS_CIRO_RISK_OVER { get; set; }
        public double? CST_CIRO_CEK_RISK_FAC { get; set; }
        public double? CST_CIRO_SENET_RISK_FAC { get; set; }
        public int? CS_CIRO_DOWNS_RISK { get; set; }
        public double? CST_CS_CIRO_RISK_LIMIT { get; set; }
        public double? REP_CST_CS_CIRO_RISK_LIMIT { get; set; }
        public double? CST_CS_CIRO_RISK_BALANCED { get; set; }
        public double? REP_CST_CS_CIRO_RISK_BALANCED { get; set; }
        public double? CST_CS_OWN_RISK_TOTAL { get; set; }
        public double? REP_CST_CS_OWN_RISK_TOTAL { get; set; }
        public double? CST_CS_CIRO_RISK_TOTAL { get; set; }
        public double? REP_CST_CS_CIRO_RISK_TOTAL { get; set; }
        public int? DESP_RISK_OVER_SUGG { get; set; }
        public double? DESP_RISK_LIMIT_SUGG { get; set; }
        public double? REP_DESP_RISK_LIMIT_SUGG { get; set; }
        public double? DESP_RISK_TOTAL_SUGG { get; set; }
        public double? REP_DESP_RISK_TOTAL_SUGG { get; set; }
        public double? DESP_RISK_BALANCED_SUGG { get; set; }
        public double? REP_DESP_RISK_BALANCED_SUGG { get; set; }
        public double? DBS_LIMIT1 { get; set; }
        public double? DBS_LIMIT2 { get; set; }
        public double? DBS_LIMIT3 { get; set; }
        public double? DBS_LIMIT4 { get; set; }
        public double? DBS_LIMIT5 { get; set; }
        public double? DBS_LIMIT6 { get; set; }
        public double? DBS_LIMIT7 { get; set; }
        public double? DBS_TOTAL1 { get; set; }
        public double? DBS_TOTAL2 { get; set; }
        public double? DBS_TOTAL3 { get; set; }
        public double? DBS_TOTAL4 { get; set; }
        public double? DBS_TOTAL5 { get; set; }
        public double? DBS_TOTAL6 { get; set; }
        public double? DBS_TOTAL7 { get; set; }
        public int? DBS_BANKNO1 { get; set; }
        public int? DBS_BANKNO2 { get; set; }
        public int? DBS_BANKNO3 { get; set; }
        public int? DBS_BANKNO4 { get; set; }
        public int? DBS_BANKNO5 { get; set; }
        public int? DBS_BANKNO6 { get; set; }
        public int? DBS_BANKNO7 { get; set; }
        public int? DBS_RSKCTRL1 { get; set; }
        public int? DBS_RSKCTRL2 { get; set; }
        public int? DBS_RSKCTRL3 { get; set; }
        public int? DBS_RSKCTRL4 { get; set; }
        public int? DBS_RSKCTRL5 { get; set; }
        public int? DBS_RSKCTRL6 { get; set; }
        public int? DBS_RSKCTRL7 { get; set; }
        public int? DBS_CURR1 { get; set; }
        public int? DBS_CURR2 { get; set; }
        public int? DBS_CURR3 { get; set; }
        public int? DBS_CURR4 { get; set; }
        public int? DBS_CURR5 { get; set; }
        public int? DBS_CURR6 { get; set; }
        public int? DBS_CURR7 { get; set; }
        public int? EINVOICE_TYPE { get; set; }
        public int? EARCHIVE_SEND_MODE { get; set; }
        public int? EARCHIVE_IS_RETAIL_AR_AP { get; set; }
        public string TITLE2 { get; set; }
        public int? ISFOREIGN { get; set; }
        public int? DEG_ACTIVE { get; set; }
        public int? DEG_CURR { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public int? LABEL_INFO { get; set; }
        public int? DUE_DATE_CONTOL1 { get; set; }
        public int? DUE_DATE_CONTOL2 { get; set; }
        public int? DUE_DATE_CONTOL3 { get; set; }
        public int? DUE_DATE_CONTOL4 { get; set; }
        public int? DUE_DATE_CONTOL5 { get; set; }
        public int? DUE_DATE_CONTOL6 { get; set; }
        public int? DUE_DATE_CONTOL7 { get; set; }
        public int? DUE_DATE_CONTOL8 { get; set; }
        public int? DUE_DATE_CONTOL9 { get; set; }
        public int? DUE_DATE_CONTOL10 { get; set; }
        public int? DUE_DATE_CONTOL11 { get; set; }
        public int? DUE_DATE_CONTOL12 { get; set; }
        public int? DUE_DATE_CONTOL13 { get; set; }
        public int? DUE_DATE_CONTOL14 { get; set; }
        public int? DUE_DATE_CONTOL15 { get; set; }
        public int? DUE_DATE_COUNT { get; set; }
        public double? DUE_DATE_LIMIT { get; set; }
        public int? DUE_DATE_TRACK { get; set; }
        public int? CLOSE_DATE_COUNT { get; set; }
        public int? CLOSE_DATE_TRACK { get; set; }
        public int? DEFBNACCREF { get; set; }
        public int? CURR_RATE_TYPE { get; set; }
        public int? INSTEAD_OF_DISPATCH { get; set; }
        public int? EINV_EARC_TYPE { get; set; }
        public int? FBS_SEND_METHOD { get; set; }
        public int? FBS_SEND_FORMAT { get; set; }
        public int? FBA_SEND_METHOD { get; set; }
        public int? FBA_SEND_FORMAT { get; set; }
        public int? PERSONEL_COSTS { get; set; }
        public int? FACTORY_DIV_NR { get; set; }
        public int? FACTORY_NR { get; set; }
        public int? IN_INVEN_NR { get; set; }
        public int? OUT_INVEN_NR { get; set; }
        public double? QTY_DEP_DURATION { get; set; }
        public double? QTY_IN_DEP_DURATION { get; set; }
        public int? OVER_LAP_TYPE { get; set; }
        public double? OVER_LAP_AMOUNT { get; set; }
        public double? OVER_LAP_PERC { get; set; }
        public int? BROKER_COMP { get; set; }
        public int? CREATE_WH_FICHE { get; set; }
        public int? EINV_CUSTOMS { get; set; }
        public int? SUB_CONT { get; set; }
        public int? ACCEPT_DESP { get; set; }
        public int? PROFILEID_DESP { get; set; }
        public int? LABEL_INFO_DESP { get; set; }
        public int? ACCEPT_EINV_PUBLIC { get; set; }
        public int? PUBLICBNACCREF { get; set; }
        public int? PUBLIC_BNACC_CURRENCY { get; set; }
        public int? KVKK_PERM_STATUS { get; set; }
        public DateTime? KVKK_BEGIN_DATE { get; set; }
        public DateTime? KVKK_END_DATE { get; set; }
        public DateTime? KVKK_CANCEL_DATE { get; set; }
        public int? KVKK_ANONYMIZE_STATUS { get; set; }
        public DateTime? KVKK_ANONYMIZE_DATE { get; set; }
        public int? EXIM_SEND_METHOD { get; set; }
        public int? EXIM_SEND_FORMAT { get; set; }
        public int? CAN_DEDUCT { get; set; }
        public int? DRIVERREF { get; set; }
        public int? EX_COUNTRY_TYPE { get; set; }
        public int? EX_COUNTRYREF { get; set; }
        public int? IM_COUNTRY_TYPE { get; set; }
        public int? IM_COUNTRYREF { get; set; }
        public int? EXIM_PAYTYPEREF { get; set; }
        public int? EXIM_BRBANKREF { get; set; }
        public int? EXIM_CUSTOMREF { get; set; }
        public int? EXIM_REGTYPEREF { get; set; }
        public int? EXIM_NOTIFYCLREF { get; set; }
        public int? EXIM_CONSULTCLREF { get; set; }
        public int? EXIM_FREIGHTCLREF { get; set; }
        public int? DISP_PRINT_CNT { get; set; }
        public int? ORD_PRINT_CNT { get; set; }
        public string GUID { get; set; }
    }
}
