using System;
using System.Collections.Generic;

namespace Logo.Siparis
{
    public class DEFNFLD
    {
        public int MODULENR { get; set; }
        public int PARENTREF { get; set; }
        public int NUMFLDS50 { get; set; }
        public string TEXTFLDS50 { get; set; }
        public int XMLATTRIBUTE { get; set; }
        public int DATAREFERENCE { get; set; }
    }

    public class DEFNFLDSLIST
    {
        public List<DEFNFLD> DEFNFLD { get; set; }
    }

    public class TRANSACTIONS
    {
        public List<Item> items { get; set; }
    }

    public class Item
    {
        public int? INTERNAL_REFERENCE { get; set; }
        public int? PARENTLNREF { get; set; }
        public int? TYPE { get; set; }
        public string MASTER_CODE { get; set; }
        public int? STOCKREF { get; set; }
        public int? ORDFICHEREF { get; set; }
        public int? CLIENTREF { get; set; }
        public int? PREVLINEREF { get; set; }
        public int? PREVLINENO { get; set; }
        public int? DETLINE { get; set; }
        public int? LINENO { get; set; }
        public int? SLIP_TYPE { get; set; }
        public DateTime? DATE { get; set; }
        public int? TIME { get; set; }
        public int? DETAIL_LEVEL { get; set; }
        public int? CALC_TYPE { get; set; }
        public string OHP_CODE1 { get; set; }
        public int? CENTERREF { get; set; }
        public string GL_CODE1 { get; set; }
        public int? ACCOUNTREF { get; set; }
        public string GL_CODE2 { get; set; }
        public int? VATACCREF { get; set; }
        public string OHP_CODE2 { get; set; }
        public int? VATCENTERREF { get; set; }
        public string GL_CODE3 { get; set; }
        public int? PRACCREF { get; set; }
        public string OHP_CODE3 { get; set; }
        public int? PRCENTERREF { get; set; }
        public string GL_CODE4 { get; set; }
        public int? PRVATACCREF { get; set; }
        public string OHP_CODE4 { get; set; }
        public int? PRVATCENREF { get; set; }
        public int? PROMREF { get; set; }
        public string AUXIL_CODE { get; set; }
        public string DELVRY_CODE { get; set; }
        public double? QUANTITY { get; set; }
        public double? PRICE { get; set; }
        public double? TOTAL { get; set; }
        public double? QUANTITY_SHIPPED { get; set; }
        public double? DISCOUNT_RATE { get; set; }
        public double? COST_DISTR { get; set; }
        public double? DISCOUNT_DISTR { get; set; }
        public double? EXPENSE_DISTR { get; set; }
        public double? PROMOTION_DISTR { get; set; }
        public double? VAT_RATE { get; set; }
        public double? VAT_AMOUNT { get; set; }
        public double? VAT_BASE { get; set; }
        public string TRANS_DESCRIPTION { get; set; }
        public string UNIT_CODE { get; set; }
        public int? UOMREF { get; set; }
        public int? USREF { get; set; }
        public double? UNIT_CONV1 { get; set; }
        public double? UNIT_CONV2 { get; set; }
        public double? UNIT_CONV3 { get; set; }
        public double? UNIT_CONV4 { get; set; }
        public double? UNIT_CONV5 { get; set; }
        public double? UNIT_CONV6 { get; set; }
        public double? UNIT_CONV7 { get; set; }
        public double? UNIT_CONV8 { get; set; }
        public int? VAT_INCLUDED { get; set; }
        public int? ORDER_CLOSED { get; set; }
        public int? ORDER_RESERVE { get; set; }
        public int? INUSE { get; set; }
        public DateTime? DUE_DATE { get; set; }
        public int? CURR_PRICE { get; set; }
        public double? PC_PRICE { get; set; }
        public double? RC_XRATE { get; set; }
        public int? BILLED_ITEM { get; set; }
        public string PAYMENT_CODE { get; set; }
        public int? PAYDEFREF { get; set; }
        public int? EXTENREF { get; set; }
        public int? COMPOSITE { get; set; }
        public int? SOURCE_WH { get; set; }
        public int? SOURCE_COST_GRP { get; set; }
        public int? DIVISION { get; set; }
        public int? DEPARTMENT { get; set; }
        public double? TOTAL_NET { get; set; }
        public int? SALESMANREF { get; set; }
        public int? ORDER_STATUS { get; set; }
        public int? DREF { get; set; }
        public int? TRGFLAG { get; set; }
        public int? DATA_SITEID { get; set; }
        public int? DATA_REFERENCE { get; set; }
        public int? FACTORY { get; set; }
        public int? NET_DSC_FLAG { get; set; }
        public double? NET_DSC_RATE { get; set; }
        public double? NET_DSC_AMOUNT { get; set; }
        public int? PRODUCED { get; set; }
        public string ORDER_CODE { get; set; }
        public int? XML_ATTRIBUTE { get; set; }
        public int? REASON_FOR_NOT_SHP { get; set; }
        public int? CMPG_LINE_REF { get; set; }
        public double? CAMPAIGN_POINT { get; set; }
        public string PROM_CLAS_ITEM_CODE { get; set; }
        public double? PR_RATE { get; set; }
        public double? GROSS_U_INFO1 { get; set; }
        public double? GROSS_U_INFO2 { get; set; }
        public int? CANCELLED { get; set; }
        public double? DEM_PEGGED_AMNT { get; set; }
        public int? TEXTINC { get; set; }
        public string SALESMAN_CODE { get; set; }
        public string PROJECT_CODE { get; set; }
        public int? PROJECTREF { get; set; }
        public int? CURR_TRANSACTIN { get; set; }
        public int? PRCLISTREF { get; set; }
        public int? AFFECT_COLLATRL { get; set; }
        public int? VARIANTREF { get; set; }
        public string VARIANTCODE { get; set; }
        public string VARIANTNAME { get; set; }
        public int? CANCONFIG { get; set; }
        public int? PRIORITY { get; set; }
        public double? ADD_TAX_RATE { get; set; }
        public double? ADD_TAX_CONVFACT { get; set; }
        public double? ADD_TAX_AMOUNT { get; set; }
        public int? ADD_TAX_ACCREF { get; set; }
        public int? ADD_TAX_CENTERREF { get; set; }
        public int? ADD_TAX_AMNTISUPD { get; set; }
        public double? ADD_TAX_DISC_AMOUNT { get; set; }
        public double? EX_ADD_TAX_RATE { get; set; }
        public double? EX_ADD_TAX_CONVF { get; set; }
        public double? EX_ADD_TAX_AMOUNT { get; set; }
        public int? EU_VAT_STATUS { get; set; }
        public int? ADD_TAX_EFFECT_KDV { get; set; }
        public int? MULTI_ADD_TAX { get; set; }
        public int? AFFECT_RISK { get; set; }
        public int? EXCLINE_INTERNAL_REFERENCE { get; set; }
        public int? EXCLINE_TRANS_REF { get; set; }
        public double? EXCLINE_PRICE { get; set; }
        public double? EXCLINE_TOTAL { get; set; }
        public double? EXCLINE_DIST_COST { get; set; }
        public double? EXCLINE_DIST_DISC { get; set; }
        public double? EXCLINE_DIST_EXP { get; set; }
        public double? EXCLINE_DIST_PROM { get; set; }
        public double? EXCLINE_VAT_AMOUNT { get; set; }
        public double? EXCLINE_VAT_MATRAH { get; set; }
        public double? EXCLINE_LINE_NET { get; set; }
        public double? EXCLINE_DIST_ADD_EXP { get; set; }
        public double? EXCLINE_NET_DISC_AMOUNT { get; set; }
        public double? EXCLINE_VAT_CALC_DIFF { get; set; }
        public double? EXCLINE_EU_VAT_AMOUNT { get; set; }
        public double? EXCLINE_ADD_TAX_AMOUNT { get; set; }
        public double? EXCLINE_ADD_TAX_CONV_FACT { get; set; }
        public double? EXCLINE_ADD_TAX_DISC_AMOUNT { get; set; }
        public double? EXCLINE_EX_ADD_TAX_AMOUNT { get; set; }
        public double? EXCLINE_EX_ADD_TAX_CONVF { get; set; }
        public double? ADD_TAX_VAT_MATRAH { get; set; }
        public double? EXCLINE_ADD_TAX_VAT_MATRAH { get; set; }
        public double? EDT_PRICE { get; set; }
        public int? EDT_CURR { get; set; }
        public DateTime? ORG_DUE_DATE { get; set; }
        public double? ORG_QUANTITY { get; set; }
        public double? ORG_PRICE { get; set; }
        public string AUXIL_CODE2 { get; set; }
        public DateTime RESERVE_DATE { get; set; }
        public double? RESERVE_AMOUNT { get; set; }
        public string PRCLISTCODE { get; set; }
        public int? PRCLISTTYPE { get; set; }
        public string GLOBAL_ID { get; set; }
        public int? DEDUCTION_PART1 { get; set; }
        public int? DEDUCTION_PART2 { get; set; }
        public int? CANDEDUCT { get; set; }
        public double? DEDUCTION_TOT { get; set; }
        public double? DEDUCTION_TOT_TC { get; set; }
        public int? OFFERREF { get; set; }
        public int? OFFTRANSREF { get; set; }
        public string PRODUCER_CODE { get; set; }
        public int? BOMREF { get; set; }
        public string BOM_CODE { get; set; }
        public int? BOM_TYPE { get; set; }
        public int? BOMREVREF { get; set; }
        public string BOM_REV_CODE { get; set; }
        public int? ROUTINGREF { get; set; }
        public string ROUTING_CODE { get; set; }
        public int? OPERATIONREF { get; set; }
        public string OPERATION_CODE { get; set; }
        public int? WSREF { get; set; }
        public string WS_CODE { get; set; }
        public string ADDITIONAL_ITEMS_CODE { get; set; }
        public string PROMOTION_CODE { get; set; }
        public int? APPLY_ADD_TAX { get; set; }
        public string VATEXCEPT_CODE { get; set; }
        public string VATEXCEPT_REASON { get; set; }
        public string ADDTAXEXCEPT_CODE { get; set; }
        public string ADDTAXEXCEPT_REASON { get; set; }
        public string CPA_CODE { get; set; }
        public string GTIP_CODE { get; set; }
        public int? PUBLICCOUNTRYREF { get; set; }
        public string PUBLIC_COUNTRY_CODE { get; set; }
        public string PUBLIC_COUNTRY_NAME { get; set; }
        public double? DIST_DISC_VAT { get; set; }
        public string DEDUCT_CODE { get; set; }
        public string DEDUCT_DEF { get; set; }
        public string GUID { get; set; }
        public string CAMPCODE1 { get; set; }
        public string CAMPCODE2 { get; set; }
        public string CAMPCODE3 { get; set; }
        public string CAMPCODE4 { get; set; }
        public string CAMPCODE5 { get; set; }
        public string PCAMPCODE { get; set; }
        public int? CAMP_LN_NO { get; set; }
    }

    public class Root
    {
        //ekledim Sevk için
        public string SHIPLOC_CODE { get; set; }
        public string SHIPLOC_DEF { get; set; }

        public TRANSACTIONS TRANSACTIONS { get; set; }
        public int? INTERNAL_REFERENCE { get; set; }
        public int? TYPE { get; set; }
        public int? CANT_CRE_DEDUCT { get; set; }
        public string PROJECT_CODE { get; set; }
        public string ARP_CODE_SHPM { get; set; }
        public string NUMBER { get; set; }
        public string DOC_TRACK_NR { get; set; }
        public DateTime? DATE { get; set; }
        public int? TIME { get; set; }
        public Int16? SOURCE_WH { get; set; }
        public Int16? SOURCE_COST_GRP { get; set; }
        public string DOC_NUMBER { get; set; }
        public string SALESMAN_CODE { get; set; }
        public string AUTH_CODE { get; set; }
        public string AUXIL_CODE { get; set; }
        public string ARP_CODE { get; set; }
        public string SHIPPING_AGENT { get; set; }
        public string GL_CODE { get; set; }
        public int? CLIENTREF { get; set; }
        public int? RECVREF { get; set; }
        public int? ACCOUNTREF { get; set; }
        public int? CENTERREF { get; set; }
        public int? UPDCURR { get; set; }
        public double? ADD_DISCOUNTS { get; set; }
        public double? TOTAL_DISCOUNTS { get; set; }
        public double? TOTAL_DISCOUNTED { get; set; }
        public double? ADD_EXPENSES { get; set; }
        public double? TOTAL_EXPENSES { get; set; }
        public double? TOTAL_PROMOTIONS { get; set; }
        public double? TOTAL_VAT { get; set; }
        public double? TOTAL_GROSS { get; set; }
        public double? TOTAL_NET { get; set; }
        public double? RC_RATE { get; set; }
        public double? RC_NET { get; set; }
        public string NOTES1 { get; set; }

        public string NOTES2 { get; set; }
        public string NOTES3 { get; set; }
        public string NOTES4 { get; set; }
        public string NOTES5 { get; set; }
        public string NOTES6 { get; set; }
        public int? EXTENREF { get; set; }
        public string PAYMENT_CODE { get; set; }
        public int? PAYDEFREF { get; set; }
        public int? PRINT_COUNTER { get; set; }
        public DateTime? PRINT_DATE { get; set; }
        public int? DIVISION { get; set; }
        public int? DEPARTMENT { get; set; }
        public int? ORDER_STATUS { get; set; }
        public int? CREATED_BY { get; set; }
        public DateTime? DATE_CREATED { get; set; }
        public int? HOUR_CREATED { get; set; }
        public int? MIN_CREATED { get; set; }
        public int? SEC_CREATED { get; set; }
        public int? MODIFIED_BY { get; set; }
        public DateTime? DATE_MODIFIED { get; set; }
        public int? HOUR_MODIFIED { get; set; }
        public int? MIN_MODIFIED { get; set; }
        public int? SEC_MODIFIED { get; set; }
        public int? SALESMANREF { get; set; }
        public string SHIPMENT_TYPE { get; set; }

        public int? CURRSEL_TOTAL { get; set; }
        public int? CURRSEL_DETAILS { get; set; }
        public int? CURR_TRANSACTIN { get; set; }


        public string TRADING_GRP { get; set; }
        public int? TEXTINC { get; set; }
        public int? DATA_SITEID { get; set; }
        public int? DATA_REFERENCE { get; set; }
        public int? FACTORY { get; set; }
        public int? XCNT { get; set; }
        public int? XML_ATTRIBUTE { get; set; }
        public string CUST_ORD_NO { get; set; }
        public int? DLV_CLIENT { get; set; }
        public int? CANCELLED { get; set; }
        public int? OFFER_REFERENCE { get; set; }
        public int? OFFALT_REFERENCE { get; set; }
        public int? OFFER_TYP { get; set; }
        public int? OFFER_ALTNR { get; set; }
        public double? TC_RATE { get; set; }
        public double? TC_NET { get; set; }
        public int? WITH_PAYMENT { get; set; }
        public int? PROJECTREF { get; set; }
        public DEFNFLDSLIST DEFNFLDSLIST { get; set; }
        public int? WFLOWCARDREF { get; set; }
        public int? OP_STATUS { get; set; }
        public int? UPD_CURR { get; set; }
        public int? UPD_TRCURR { get; set; }
        public int? GUARANTOR1_FICHETYPE { get; set; }
        public int? GUARANTOR1_NR { get; set; }
        public int? GUARANTOR1_SITEID { get; set; }
        public int? GUARANTOR1_ORGLOGICREF { get; set; }
        public int? GUARANTOR1_CLIENTREF { get; set; }
        public int? GUARANTOR2_FICHETYPE { get; set; }
        public int? GUARANTOR2_NR { get; set; }
        public int? GUARANTOR2_SITEID { get; set; }
        public int? GUARANTOR2_ORGLOGICREF { get; set; }
        public int? GUARANTOR2_CLIENTREF { get; set; }
        public int? AFFECT_COLLATRL { get; set; }
        public double? TOTAL_ADD_TAX { get; set; }
        public double? TOTAL_EX_ADD_TAX { get; set; }
        public int? AFFECT_RISK { get; set; }
        public int? EXCHINFO_INTERNAL_REFERENCE { get; set; }
        public int? EXCHINFO_FICHE_REF { get; set; }
        public double? EXCHINFO_ADD_DISCOUNTS { get; set; }
        public double? EXCHINFO_TOTAL_DISCOUNTS { get; set; }
        public double? EXCHINFO_TOTAL_DISCOUNTED { get; set; }
        public double? EXCHINFO_ADD_EXPENSES { get; set; }
        public double? EXCHINFO_TOTAL_EXPENSES { get; set; }
        public double? EXCHINFO_DIST_EXPENSE { get; set; }
        public double? EXCHINFO_TOTAL_DEPOZITO { get; set; }
        public double? EXCHINFO_TOTAL_PROMOTIONS { get; set; }
        public double? EXCHINFO_VAT_INC_GROSS { get; set; }
        public double? EXCHINFO_TOTAL_VAT { get; set; }
        public double? EXCHINFO_GROSS_TOTAL { get; set; }
        public double? EXCHINFO_TOTAL_ADD_TAX { get; set; }
        public double? EXCHINFO_TOTAL_EX_ADD_TAX { get; set; }
        public double? EXCHINFO_BAGKUR { get; set; }
        public double? EXCHINFO_STOPAJ { get; set; }
        public double? EXCHINFO_SSDF { get; set; }
        public double? EXCHINFO_BORSA { get; set; }
        public double? EXCHINFO_KOMISYON { get; set; }
        public double? EXCHINFO_KOM_KDV { get; set; }
        public double? EXCHINFO_EK1 { get; set; }
        public double? EXCHINFO_EK2 { get; set; }
        public double? EXCHINFO_EK3 { get; set; }
        public double? EXCHINFO_EK4 { get; set; }
        public double? EXCHINFO_EK5 { get; set; }
        public int? PAYMENT_TYPE { get; set; }
        public int? APPROVE { get; set; }
        public DateTime? APPROVE_DATE { get; set; }
        public string GUID { get; set; }
        public int? DEDUCTIONPART1 { get; set; }
        public int? DEDUCTIONPART2 { get; set; }
        public int? CANCEL_AUTO_CAMP_PROC { get; set; }
        public int? APPLY_ARP_DISCOUNT { get; set; }
        public int? DEVIR { get; set; }
        public DateTime ORIGINAL_DATE { get; set; }
        public int? ACTIVITY_RENTING { get; set; }
        public double? ADD_DISCOUNTS_VAT { get; set; }
        public int? EINVOICE_TYPE { get; set; }
        public string VATEXCEPT_CODE { get; set; }
        public string VATEXCEPT_REASON { get; set; }
        public int? EINVOICE { get; set; }
        public int? EINVOICE_PROFILEID { get; set; }
        public int? EINVOICE_STATUS { get; set; }
        public DateTime? EINVOICE_STARTDATE { get; set; }
        public DateTime? EINVOICE_ENDDATE { get; set; }
        public double? EINVOICE_DURATION { get; set; }
        public int? EINVOICE_DURATIONTYPE { get; set; }
        public int? EINVOICE_TAXTYPE { get; set; }
        public DateTime? EINVOICE_TUPASSPORTDATE { get; set; }
        public int? EINVOICE_TRANSPORTTYP { get; set; }
        public DateTime? EINVOICE_EXITDATE { get; set; }
        public int? EINVOICE_EXITTIME { get; set; }
        public double? EINVOICE_TURETPRICE { get; set; }
        public int? EINVOICE_SENDEINVCUSTOM { get; set; }
        public int? EINVOICE_EINVOICETYPSGK { get; set; }
        public int? EINVOICE_CHAINDELIVERY { get; set; }
        public int? EINVOICE_SELLERCLIENTREF { get; set; }
        public int? PUBLICBNACCREF { get; set; }
        public int? PUBLIC_BNACC_CURRENCY { get; set; }
        public int? ACCEPT_EINV_PUBLIC { get; set; }
        public int? EINSTEAD_OF_DISPATCH { get; set; }
        public int? TAX_FREE_CHECK { get; set; }
        public int? EARCHIVEDETR_LOGICALREF { get; set; }
        public int? EARCHIVEDETR_ORDFCREF { get; set; }
        public int? EARCHIVEDETR_EARCHIVESTATUS { get; set; }
        public int? EARCHIVEDETR_EARCHIVESTATUSOLD { get; set; }
        public int? EARCHIVEDETR_SENDMOD { get; set; }
        public int? EARCHIVEDETR_INTPAYMENTTYPE { get; set; }
        public int? EARCHIVEDETR_INTPAYMENTDATEORG { get; set; }
        public int? EARCHIVEDETR_OCKFICHEDATEORG { get; set; }
        public int? EARCHIVEDETR_ISCOMP { get; set; }
        public int? EARCHIVEDETR_ISPERCURR { get; set; }
        public int? EARCHIVEDETR_INSTEADOFDESP { get; set; }
        public int? EARCHIVEDETR_CHAINDELIVERY { get; set; }
        public int? EARCHIVEDETR_SELLERCLIENTREF { get; set; }
        public int? PAYERTYPE { get; set; }
    }



}