using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LOGO_XERO.Models.LOGO_M
{
    public class L_FIRMPARAMS
    {
        [Key]
        public int LOGICALREF { get; set; }

        public Int16 FIRMNR { get; set; }

        public Int16? MODULENR { get; set; }

        public Int16? GROUPNR { get; set; }

        public string CODE { get; set; }

        public string VALUE { get; set; }
    }

    //FIN_PURDEFVATRATE MODULENR = 11 GROUPNR=1 SATINALMA KDV ORANI
    //FIN_SALDEFVATRATE MODULENR = 11 GROUPNR=2 SATIŞ KDV ORANI
    //FIN_RETDEFVATRATE MODULENR = 11 GROUPNR=3  İADE KDV ORANI
    //FIN_SALPERDEFVATRATE MODULENR = 11 GROUPNR=59 PERAKENDE SATIŞ KDV ORANI
    //FIN_RETPERDEFVATRATE MODULENR = 11 GROUPNR=60 PERAKENDE İADE KDV ORANI


    //PURCH_DEDUCTIONPART1 MODULENR = 9 GROUPNR=85 SATINALMA TEVKIFATCARPAN
    //PURCH_DEDUCTIONPART2 MODULENR = 9 GROUPNR=86 SATINALMA TEVKIFATBOLEN
    //SALES_DEDUCTIONPART1 MODULENR = 10 GROUPNR=85  SATIŞ TEVKIFATCARPAN
    //SALES_DEDUCTIONPART2 MODULENR = 10 GROUPNR=86 SATIŞ TEVKIFATBOLEN

    //ITEM_UNITSETREF  MODULENR = 1 GROUPNR=40 STOK KARTI STANDART BİRİM SETİ REFERANSI 

    //cari kart vade takibi modülü parametreleri

    //VADE TAKİBİNDE YAPILACAK İŞLEMLER
    //FIN_DUEDATECONTBANKBATCH  MODULENR == 11 GROUPNR == 162  BANKA İŞLEMİ
    //FIN_DUEDATECONTCHBATCH  MODULENR == 11 GROUPNR == 162  CARİ HESAP İŞLEMLERİ
    //FIN_DUEDATECONTEXIM  MODULENR == 11 GROUPNR == 162  İHRACAT
    //FIN_DUEDATECONTKSBATCH  MODULENR == 11 GROUPNR == 162  KASA İŞLEMLERİ
    //FIN_DUEDATECONTSALINV  MODULENR == 11 GROUPNR == 162  SATIŞ FATURALARI
    //FIN_DUEDATECONTSALORD  MODULENR == 11 GROUPNR == 162  SATIŞ SİPARİŞLERİ


    //FIN_DUEDATECOUNT  MODULENR == 11 GROUPNR == 163 VADE TAKİBİ YAPILACAK GÜN SAYISI
    //FIN_DUEDATELIMIT  MODULENR == 11 GROUPNR == 164 VADE TAKİBİ LİMİTİ
    //FIN_DUEDATETRACK  MODULENR == 11 GROUPNR == 165 VADE TAKİBİ YAPILDIĞINDA 
    //FIN_ACCRISKLIMIT  MODULENR == 11 GROUPNR == 382 AÇIK HESAP RİSK LİMİTİ

    //RİSK TOPLAMINDA

    //FIN_RISKTYPES1 MODULENR == 11 GROUPNR == 109 AÇIK HESAP
    //FIN_RISKTYPES2 MODULENR == 11 GROUPNR == 109 KENDİ ÇEK SENET
    //FIN_RISKTYPES3 MODULENR == 11 GROUPNR == 109 MUSTERİ ÇEK SENET
    //FIN_RISKTYPES4 MODULENR == 11 GROUPNR == 109 IRSALIYE
    //FIN_RISKTYPES5 MODULENR == 11 GROUPNR == 109 SİPARİŞ SEVKEDİLEBİLİR
    //FIN_RISKTYPES6 MODULENR == 11 GROUPNR == 109 SİPARİŞ ÖNERİ
    //FIN_RISKTYPES7 MODULENR == 11 GROUPNR == 109 CİRO ÇEK SENET
    //FIN_RISKTYPES8 MODULENR == 11 GROUPNR == 109 İRSALİYE ÖNERİ

    //KDV MUAFİYET KONTROLÜ YAPILACAK İŞLEMLER
    //SALES_SVATEXCCODETYP1 MODULENR == 10 GROUPNR == 400 SİPARİŞ
    //SALES_SVATEXCCODETYP2 MODULENR == 10 GROUPNR == 400 İRSALİYE
    //SALES_SVATEXCCODETYP3 MODULENR == 10 GROUPNR == 400 FATURA

    //SALES_SVATEXCEPTCODECTRL MODULENR == 10 GROUPNR == 350 KDV MUAFİYET KONTROLÜ YAPILACAK


}
